### ISSUE TITLE
App crashes after RNRestart.Restart()

### ISSUE THREAD

**Issue by akhlopyk** [avishayil/react-native-restart#121]
HI,
Not sure if this somehow related to this library but after RNRestart.Restart()
my app crashes with this warning. Ay ideas about it? 

The same for both platform.

" Unable to find module for ViewManager "

**Comment by avishayil** [comment]
Hi @akhlopyk , can you please try to replicate the issue with a fresh project and see if it is still happening? It will give you a better clue if it happens because of this library or not.

**Comment by avishayil** [comment]
I just tried to replicate this with the updated example app, no success...

**Comment by ErHarinderSingh** [comment]
Same for me. App crash in release build. But metro bundle reloaded in debugging build. May be it is issues with library. Like it's compatible with hermes-engine? Try to use without hermes enabled. 
Make me sure that library is for both release and debugging builds? Or only for debugging? If debugging then it's works for me. But if for both it's not working in release build.

**Comment by ErHarinderSingh** [comment]
But now it's not required any external library to restart in debugging mode.
Check official docs. https://reactnative.dev/docs/devsettings#reload

**Comment by avishayil** [comment]
Hi @ErHarinderSingh , I just tested this on the example app for both iOS and Android, it works just fine for both release and debug builds.
This library is meant for production, because on debug you have RN DevTools of course.

**Comment by ErHarinderSingh** [comment]
> Hi @ErHarinderSingh , I just tested this on the example app for both iOS and Android, it works just fine for both release and debug builds.
> This library is meant for production, because on debug you have RN DevTools of course.

Can we do restart from root component only? Or we can do from any child component too? Because I am trying to do from sidebar drawer. I am changing language of the app from dropdown and then calling restart but then app crashed. What will be the problem?

**Comment by akhlopyk** [comment]
@avishayil 
Agree, looks like I found the solution of my issue.
The thing was with calling restart not in the first place once I got used data. (I need it to change language). Once I made it right after fetching - looks like it does it's job. Thanks!

**Comment by FakhruddinAbdi** [comment]
I'm using this library and after releasing it on google play, I see many crashes reporting from google play and cCrashlytic.

I'm using RNR for changing language, and it works, But apparently, the crash monitoring tools consider it as a crash

**Comment by tkyr-hh** [comment]
I've faced the same issue before with this library, but it has been resolved by putting RNRestart.Restart() after any other method, if these methods are asynchronous put the restart after the await or .then() callback ... if not  put it inside a `setTimeout(()=>  RNRestart.Restart(), someMilliSec);` in order to make sure that they are all finish there work. 
I hope this helps, sorry for my torrible English.

**Comment by elabayoub** [comment]
If still crashes on Android even after using timeout, you can either use this : https://github.com/avishayil/react-native-restart/pull/211/files (worked for me but still crashed on Android 11) and run npx patch-package react-native-restart

**OR** add below code (worked for me on Android 11 >) in restart fun():

> @ReactMethod
public void Restart() {
Intent intent = getReactApplicationContext().getBaseContext().getPackageManager().getLaunchIntentForPackage(getReactApplicationContext().getBaseContext().getPackageName() );
intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
getReactApplicationContext().startActivity(intent);
android.os.Process.killProcess(android.os.Process.myPid());
System.exit(0);
}

and run npx patch-package react-native-restart
