### ISSUE TITLE
/node_modules/react-native-restart: Appears to be a git repo or submodule

### ISSUE THREAD

**Issue by L-x-C** [avishayil/react-native-restart#71]
when i run 
```
npm install 
```
with package.json

will show

```
npm ERR! path /Users/liuxiaocong/mutualFund/domestic-app/node_modules/react-native-restart
npm ERR! code EISGIT
npm ERR! git /Users/liuxiaocong/mutualFund/domestic-app/node_modules/react-native-restart: Appears to be a git repo or submodule.
npm ERR! git     /Users/liuxiaocong/mutualFund/domestic-app/node_modules/react-native-restart
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuxiaocong/.npm/_logs/2019-04-09T06_15_40_005Z-debug.log
```

**Comment by L-x-C** [comment]
The reason that caused the problem is you did't ignore your .git in your .npmignore.
I've made a PR to fix this, plz merge it.

https://github.com/avishayil/react-native-restart/pull/72

![image](https://user-images.githubusercontent.com/4329120/55794625-4656e580-5af8-11e9-95b4-dcfc4fe68c18.png)

**Comment by allan-cornet-eove** [comment]
Please release 0.0.11

**Comment by iyucef** [comment]
any update about this issue because this bug is still available with 0.0.10

**Comment by a-koka** [comment]
Using version 0.0.9 works for now

**Comment by drakonkat** [comment]
When the fix will be released?

**Comment by esbozos** [comment]
a temporal workaround while the fix is released, simply remove the .git folder from node_modules

`rm -rf node_modules/react-native-restart/.git/`

**Comment by sarthakmis** [comment]
> a temporal workaround while the fix is released, simply remove the .git folder from node_modules
> 
> `rm -rf node_modules/react-native-restart/.git/`

Worked For me

**Comment by allan-cornet-eove** [comment]
An minimal npm release will be the best workaround ...

**Comment by mwkthang1** [comment]
I am having the same problem on my **windows** system. 
Any solution? 
Please help!

**Comment by avishayil** [comment]
Fixed in https://github.com/avishayil/react-native-restart/commit/be6518bbe68ec5d966d2bfdd7f95ff94f846d306

**Comment by tuanitpro** [comment]
> a temporal workaround while the fix is released, simply remove the .git folder from node_modules
> 
> `rm -rf node_modules/react-native-restart/.git/`
Worked For me

**Comment by SaeedZhiany** [comment]
> Fixed in [be6518b](https://github.com/avishayil/react-native-restart/commit/be6518bbe68ec5d966d2bfdd7f95ff94f846d306)

I'm still having the problem
My case is like below:
installing the library for the first time (react-native-restart does not exist in node_modules) everything is fine,
but when it exists in the folder and I'm trying to install another library with command `npm install`, the procedure failed with the same error message @L-x-C reported.
